$ProjectName = '<%= VmName %>'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "<%= VmImageName %>"
  config.vm.hostname = "#{$ProjectName}"<% if (ServiceApache) { %>
  config.vm.network "forwarded_port", guest: 80, host: 8000<% } if (ServiceMysql) { %>
  config.vm.network :forwarded_port, guest: 3306, host: 33060<% } if (ServiceTomcat) { %>
  config.vm.network :forwarded_port, guest: 8080, host: 8888<% } %>
  config.vm.network :private_network, ip: "<%= VmPrivateIp %>"
  config.vm.provider "virtualbox" do |v|
    v.memory = <%= VmMemory %>
    v.cpus = <%= VmCpus %>
  end<% if (VmProvision != 'none') { %>

  config.vm.provision :shell, path: "bootstrap.sh"<% } %>

end
